version: '3'

services:
  ApacheServer:
    image: httpd:latest
    container_name: apache-10.9.0.2
    cap_add:
      - ALL
    privileged: true
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.2
    ports:
      - "80:80"

  Attacker:
    image: ubuntu:latest
    container_name: attacker-10.9.0.3
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.3
    command: bash -c "
              apt-get update && apt-get install -y openbsd-inetd &&
              /etc/init.d/openbsd-inetd start  &&
              cd /volumes &&
              make &&
              ./syn_flood &&
              tail -f /dev/null"
    cap_add:
      - ALL
    privileged: true
    volumes:
      - ./volumes:/volumes

  Monitor:
    image: ubuntu:latest
    container_name: monitor-all
    network_mode: host
    command: bash -c "
              apt-get update && apt-get install -y openbsd-inetd &&
              /etc/init.d/openbsd-inetd start &&
              ping -i 1 10.9.0.2 > /volumes/ping_results.txt &&
              tail -f /dev/null"
    cap_add:
      - ALL
    privileged: true
    volumes:
      - ./volumes:/volumes

networks:
  net-10.9.0.0:
    driver: bridge
    ipam:
      config:
        - subnet: 10.9.0.0/24
