version: '3'
services:
  ApacheServer:
    image: httpd:latest
    container_name: apache-10.9.0.2
    cap_add:
      - ALL
    privileged: true
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.2
    ports:
      - "80:80"
    volumes:
      - ./volumes:/volumes
    command: >
      bash -c "
      apt-get update &&
      apt-get install -y net-tools tcpdump &&
      echo \"Container started at: $$(date)\" > /volumes/netstat_output.txt &&
      httpd-foreground &
      while true; do
        echo \"Timestamp: $$(date)\" >> /volumes/netstat_output.txt
        netstat -tuna >> /volumes/netstat_output.txt
        echo \"----------------------------------------\" >> /volumes/netstat_output.txt
        sleep 10
      done"

  Attacker:
    image: gcc:latest
    container_name: attacker-10.9.0.3
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.3
    volumes:
      - ./volumes:/volumes
    command: >
      bash -c "
      cd /volumes &&
      gcc -o syn_flood syn_flood.c -lm &&
      sleep 20 &&
      ./syn_flood"
    cap_add:
      - ALL
    privileged: true

  Monitor:
    image: ubuntu:latest
    container_name: monitor-all
    network_mode: host
    command: >
      bash -c "
      apt-get update &&
      apt-get install -y iputils-ping &&
      mkdir -p /volumes &&
      echo \"Container started at: $$(date)\" > /volumes/ping.txt &&
      while true; do
        echo \"Timestamp: $$(date)\" >> /volumes/ping.txt
        ping -c 1 10.9.0.2 | tee -a /volumes/ping.txt
        echo '---' >> /volumes/ping.txt
        sleep 5
      done"
    cap_add:
      - ALL
    privileged: true
    volumes:
      - ./volumes:/volumes

networks:
  net-10.9.0.0:
    driver: bridge
    ipam:
      config:
        - subnet: 10.9.0.0/24